"""
reflection.py — end-of-run lesson synthesis
============================================

Reads the last N learning rows for a brand and asks Claude Opus to distill
patterns into 3-5 actionable lessons. Writes the result to
`brands/<brand>/_lessons.md`.

The manager loads this file at the start of every subsequent run and injects
the top lessons into each brain-agent's system prompt, closing the loop:
last run's failures → next run's prompt enhancement.
"""
from __future__ import annotations

import json
from datetime import datetime

from agents.llm_client import complete as llm_complete
from agents.learning.memory_store import read_recent_runs, write_lessons


# Compact view sent to the LLM so we don't blow context on raw JSON
def _compress_rows(rows: list[dict]) -> str:
    lines = []
    for r in rows[-20:]:
        q = r.get("quality") or {}
        composite = q.get("composite")
        ag = q.get("anti_generic")
        viols = r.get("violations") or []
        line = (
            f"[{r.get('timestamp','?')}] agent={r.get('agent','?')} "
            f"composite={composite} anti_generic={ag} "
            f"retries={r.get('retries',0)} healed={r.get('healed', False)} "
            f"violations={'; '.join(viols)[:140] if viols else 'none'} "
            f"output=\"{(r.get('output_summary') or '')[:140]}\""
        )
        lines.append(line)
    return "\n".join(lines)


SYSTEM_PROMPT = (
    "You are a senior content-strategy operator reviewing the recent run log "
    "of an autonomous social-media-marketing system. Your job is to find "
    "PATTERNS — recurring issues, recurring strengths, and concrete things to "
    "do differently next run. Be specific. Cite the agent name and the kind "
    "of violation. Do not produce generic advice ('be more specific') — name "
    "the exact rule the agents should follow next time, drawn from the data."
)


def _user_prompt(brand_name: str, niche: str, rows_block: str) -> str:
    return (
        f"BRAND: {brand_name}  NICHE: {niche}\n\n"
        f"RECENT RUN LOG ({len(rows_block.splitlines())} rows):\n"
        f"{rows_block}\n\n"
        "Write a markdown document with three sections:\n\n"
        "## What's working\n"
        "3-5 bullets. Each bullet must reference an agent and a concrete pattern "
        "from the data — not a platitude.\n\n"
        "## What's failing\n"
        "3-5 bullets. Each must name the agent + the specific violation pattern.\n\n"
        "## Rules for the next run\n"
        "3-5 imperative rules an LLM agent can follow literally. Each starts "
        "with a verb. Be concrete: name the field, the regex, the structure, "
        "the banned word — not 'improve quality'.\n\n"
        "Keep the whole document under 400 words. No preamble."
    )


async def synthesize_lessons(brand_name: str, niche: str = "") -> str:
    """Read recent runs, call Claude Opus, write _lessons.md, return the text."""
    rows = read_recent_runs(brand_name, limit=20)
    if len(rows) < 3:
        # Not enough data to synthesize — leave the existing lessons in place.
        return ""

    rows_block = _compress_rows(rows)
    try:
        text = await llm_complete(
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": _user_prompt(brand_name, niche, rows_block)},
            ],
            tier="brain",
            temperature=0.3,
            max_tokens=1200,
        )
    except Exception as ex:
        print(f"[reflection] synthesis failed: {ex}")
        return ""

    if not text:
        return ""

    header = (
        f"<!-- generated by agents/learning/reflection.py at "
        f"{datetime.utcnow().isoformat()} from {len(rows)} runs -->\n\n"
        f"# Lessons for {brand_name}\n\n"
    )
    full = header + text.strip() + "\n"
    write_lessons(brand_name, full)
    return full


def top_lessons_for_prompt(brand_name: str, max_chars: int = 1200) -> str:
    """Return the lessons file content, truncated for prompt injection.

    Synchronous — meant to be called at the start of every agent prompt
    build to slot under a 'LEARNED_PATTERNS' header.
    """
    from agents.learning.memory_store import read_lessons
    text = read_lessons(brand_name)
    if not text:
        return ""
    return text[:max_chars]
